/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIFold: typeof import('element-plus/es')['ElIFold']
    Hamburger: typeof import('./components/Hamburger.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpUnfold: typeof import('~icons/ep/unfold')['default']
  }
}
